---
ops: [train, ct_masked_train]
lr: 0.0001
lr_scheduler: {
    class: !import torch.optim.lr_scheduler.CosineAnnealingLR,
    class_args: {
        T_max: 409070,  # train_loader_len(batch_size) * n_epochs  = 409070
    }
}
model: {
    path: src/deepct_model_multi_ct.py,
    class: DeepCT,
    # checkpoint_resume: ,
    checkpoint_resume: DeepCT_outputs/biox/ct_v2/dnase/multi_ct/kfold_crossval_LR0001_folds_shuffle/fold_00/checkpoint.pth.tar, 
    checkpoint_epoch: 7,
    checkpoint_chunk: 7,
    class_args: {
        sequence_length: 1000,
        n_cell_types: 631,
        sequence_embedding_length: 256,
        cell_type_embedding_length: 32,
        final_embedding_length: 256,
        n_genomic_features: 1,
    }
}
criterion: !obj:torch.nn.BCEWithLogitsLoss {
    reduction: 'sum',
}
dataset: {
    debug: False,
    path: src/dataset.py,
    class: EncodeDataset,
    ct_fold_ids: /mnt/datasets/DeepCT/results/ct_random_ids_k10.npy,
    seq_fold_ids: /mnt/datasets/DeepCT/results/splitted_intervals_hold.npy,
    train_sampler_class: LargeRandomSampler,
    train_sampler_args: {replacement: False},
    validation_sampler_class: SubsetRandomSampler,
    validation_sampler_args: {num_samples: 100000},
    
    distinct_features_path: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/dnase/distinct_features.txt,
    target_features_path: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/dnase/target_features.txt,
    sampling_intervals_path: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/dnase/target_intervals.bed,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],
    
    dataset_args: {
        reference_sequence_path: /mnt/datasets/DeepCT/male.hg19.fasta,
        target_path: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/dnase/sorted_data.bed.gz,
        cell_wise: True,
        multi_ct_target: True,
        sequence_length: 1000,
        center_bin_to_predict: 200,
        feature_thresholds: 0.5,
        position_skip: 120,
        n_folds: 10,                    
        fold: 0,                        # !!!
    },
    loader_args: {
        batch_size: 256,  # !!!
        num_workers: 16,
    },
    train_transform: !obj:torchvision.transforms.Compose {
        transforms: [
            !obj:src.transforms.PermuteSequenceChannels {},
            !obj:src.transforms.RandomReverseStrand {
                p: 0.5,
            }
        ],
    },
    val_transform: !obj:src.transforms.PermuteSequenceChannels {}
}
train_model: !obj:src.train.ct_masked_train.TrainEncodeDatasetModel {
    n_epochs: 10,  # !!!
    report_stats_every_n_steps: 2000,
    save_checkpoint_every_n_steps: 2000,
    report_gt_feature_n_positives: 10,
    device: 'cuda:3',
    data_parallel: False,
    logging_verbosity: 2,
    metrics: {
#        accuracy: !import src.metrics.accuracy_score,
        average_precision: !import sklearn.metrics.average_precision_score,
        # jaccard_score: !import sklearn.metrics.jaccard_score,
#        f1: !import src.metrics.f1_score,
#        precision: !import src.metrics.precision_score,
#        recall: !import src.metrics.recall_score,
        # roc_auc: !import sklearn.metrics.roc_auc_score,
    },
    # log_confusion_matrix: False,
}
output_dir: DeepCT_outputs/biox/ct_v2/dnase/multi_ct/kfold_crossval_LR0001_folds_shuffle/fold_00/

random_seed: 1447
create_subdirectory: False
...
