---
ops: [train, ct_masked_train]
lr: 0.0001
lr_scheduler: {
    class: !import torch.optim.lr_scheduler.CosineAnnealingLR,
    class_args: {
        T_max: 1308200,
    }
}
model: {
    path: src/deepct_model_multi_ct.py,
    class: DeepCT,
    checkpoint_resume: ,
    checkpoint_epoch: 0,
    checkpoint_chunk: 0,
    class_args: {
        sequence_length: 1000,
        n_cell_types: 174,
        sequence_embedding_length: 256,
        cell_type_embedding_length: 32,
        final_embedding_length: 256,
        n_genomic_features: 4,
    }
}
criterion: !obj:torch.nn.BCEWithLogitsLoss {
    reduction: 'sum',
}
dataset: {
    debug: False,
    path: src/dataset.py,
    class: EncodeDataset,
    ct_fold_ids: dataset_data/Biox_et_al/complete_clique14_with0/cell_types_random_ids_k10_seed2454.npy,
    seq_fold_ids: dataset_data/Biox_et_al/complete_clique14_with0/split_intervals_no_overlap_k10_seed2454.npy,
    train_sampler_class: LargeRandomSampler,
    train_sampler_args: {replacement: False},

    distinct_features_path: dataset_data/Biox_et_al/complete_clique14_with0/distinct_features.txt,
    target_features_path: dataset_data/Biox_et_al/complete_clique14_with0/target_features.txt,
    sampling_intervals_path: dataset_data/Biox_et_al/complete_clique14_with0/target_intervals.bed,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],

    dataset_args: {
        reference_sequence_path: dataset_data/male.hg19.fasta,
        cell_wise: True,
        multi_ct_target: True,
        sequence_length: 1000,
        center_bin_to_predict: 200,
        feature_thresholds: 0.5,
        position_skip: 200,
        n_folds: 10,                    
        fold: 7,
        target_class: !import selene_sdk.targets.GenomicFeatures,
        target_init_kwargs: {
            input_path: dataset_data/complete_clique14_with0/sorted_data.bed.gz, 
            feature_thresholds: 0.5,
        },
    },
    loader_args: {
        batch_size: 256,
        num_workers: 16,
        pin_memory: True,
    },
    train_transform: !obj:torchvision.transforms.Compose {
        transforms: [
            !obj:src.transforms.PermuteSequenceChannels {},
            !obj:src.transforms.RandomReverseStrand {
                p: 0.5,
            }
        ],
    },
    val_transform: !obj:torchvision.transforms.Compose {
        transforms: [
            !obj:src.transforms.PermuteSequenceChannels {},
        ]
    }
}

train_model: !obj:src.train.ct_masked_train.TrainMaskedCTModel {
    n_epochs: 40,
    report_gt_feature_n_positives: 2,
    device: 'cuda:1',
    data_parallel: False,
    logging_verbosity: 2,
    metrics: {
        average_precision: !import sklearn.metrics.average_precision_score,
    },
    metrics_transforms: {
        average_precision: !import src.transforms.scores2prob_transform,
    },
    log_confusion_matrix: False,
}
output_dir: DeepCT_outputs/boix/ct_v2/complete_clique14_with0_fix/kfold_10folds_LR0001/no_overlap/seed3793/

random_seed: 3793
create_subdirectory: False