---
ops: [train]
lr: 0.0001
lr_scheduler: {
    class: !import torch.optim.lr_scheduler.CosineAnnealingLR,
    class_args: {
        T_max: 1750020,
    }
}
model: {
    path: src/deepct_model_multi_ct_q.py,
    class: qDeepCT,
    class_args: {
        sequence_length: 1000,
        n_cell_types: 1,
        sequence_embedding_length: 256,
        cell_type_embedding_length: 32,
        final_embedding_length: 256,
        n_genomic_features: 1,
    }
}
criterion: !obj:src.criterion.WeightedMSELoss {
    pos_weight: !obj:numpy.genfromtxt {
        fname: '/mnt/datasets/DeepCT/dataset_data/q_features_DNAse/pos_weights.txt'
        }
}

dataset: {
    path: src/dataset.py,
    class: EncodeDataset,
    train_sampler_class: LargeRandomSampler,
    train_sample_args: {replacement: False},
    validation_sampler_class: SubsetRandomSampler,
    validation_sampler_args: {num_samples: 6400},

    distinct_features_path: /mnt/datasets/DeepCT/dataset_data/all_features_q_test/distinct_features.txt,
    target_features_path: /mnt/datasets/DeepCT/dataset_data/all_features_q_test/target_features.txt,
    sampling_intervals_path: /mnt/datasets/DeepCT/dataset_data/all_features_q_test/target_intervals.bed,
    quantitative_features: True,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],

    dataset_args: {
        reference_sequence_path: /mnt/datasets/DeepCT/male.hg19.fasta,
        target_path: /mnt/datasets/DeepCT/dataset_data/all_features_q_test/testqDatasetMapping.tsv,
        cell_wise: True,
        multi_ct_target: True,
        sequence_length: 1000,
        center_bin_to_predict: 200,
        feature_thresholds: 0.5,
        position_skip: 120,
    },
    loader_args: {
        batch_size: 64,
        num_workers: 16,
    },
    train_transform: !obj:torchvision.transforms.Compose {
        transforms: [
            !obj:src.transforms.PermuteSequenceChannels {},
            !obj:src.transforms.RandomReverseStrand {
                p: 0.5,
            }
        ],
    }
}
train_model: !obj:src.train.train_encode_dataset.TrainEncodeDatasetModel {
    n_epochs: 10,
    report_stats_every_n_steps: 2000,
    save_checkpoint_every_n_steps: 2000,
    report_gt_feature_n_positives: 10,
    device: 'cpu',
    data_parallel: False,
    logging_verbosity: 2,
    metrics: {
 #       accuracy: !import src.metrics.accuracy_score,
#        average_precision: !import sklearn.metrics.average_precision_score,
#        f1: !import src.metrics.f1_score,
#        precision: !import src.metrics.precision_score,
#        recall: !import src.metrics.recall_score,
#        roc_auc: !import sklearn.metrics.roc_auc_score,
        mse: !import sklearn.metrics.mean_squared_error
    },
}
<<<<<<< HEAD
output_dir: DeepCT_outputs/tests/boix/ct_v2/q/DNAse_all_ct/WeightedMSELoss/
=======
output_dir: DeepCT_outputs/code_tests/boix/ct_v2/all/multi_ct/q/WeightedMSELoss/
>>>>>>> Add new subsampler sampler to speed up validation metrix computation

random_seed: 1447
create_subdirectory: True
...
