---
ops: [train, evaluate]
lr: 0.0001
lr_scheduler: {
    class: !import torch.optim.lr_scheduler.CosineAnnealingLR,
    class_args: {
        T_max: 630250,
    }
}
model: {
    path: src/deepct_model_multi_ct.py,
    class: DeepCT,
    class_args: {
        sequence_length: 1000,
        n_cell_types: 858,
        sequence_embedding_length: 256,
        cell_type_embedding_length: 32,
        final_embedding_length: 256,
        n_genomic_features: 40,
    }
}
criterion: !obj:torch.nn.BCEWithLogitsLoss {
    reduction: 'sum',
}
dataset: {
    path: src/dataset.py,
    class: EncodeDataset,
    sampler_class: LargeRandomSampler,

    distinct_features_path: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/distinct_features.txt,
    target_features_path: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/target_features.txt,
    sampling_intervals_path: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/target_intervals.bed,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],

    dataset_args: {
        reference_sequence_path: /mnt/datasets/DeepCT/male.hg19.fasta,
        target_class: !import selene_sdk.targets.GenomicFeatures,
        target_init_kwargs: {
            input_path: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/complete_clique1_with0/sorted_data.bed.gz,
            feature_thresholds: 0.5,
        },
        target_path: None,
        cell_wise: True,
        multi_ct_target: True,
        sequence_length: 1000,
        center_bin_to_predict: 200,
        feature_thresholds: 0.5,
        position_skip: 120,
    },
    loader_args: {
        batch_size: 256,
        num_workers: 16,
    },
    train_transform: !obj:torchvision.transforms.Compose {
        transforms: [
            !obj:src.transforms.PermuteSequenceChannels {},
            !obj:src.transforms.RandomReverseStrand {
                p: 0.5,
            },
        ],
    }
}
train_model: !obj:src.train.train_encode_dataset.TrainEncodeDatasetModel {
    n_epochs: 10,
    report_stats_every_n_steps: 1000,
    save_checkpoint_every_n_steps: 2000,
    report_gt_feature_n_positives: 10,
    device: 'cuda:2',
    data_parallel: False,
    logging_verbosity: 2,
    metrics: {
        average_precision: !import sklearn.metrics.average_precision_score,
    },
}
output_dir: DeepCT_outputs/boix/ct_v2/all/multi_ct/AdamW_COS_LR0001

random_seed: 1447
create_subdirectory: True
...