---
ops: [train, ct_masked_train]
lr: 0.0001
lr_scheduler: {
    class: !import torch.optim.lr_scheduler.CosineAnnealingLR,
    class_args: {
        T_max: 1085430, # total number of training steps
    }
}
model: {
    path: src/deepct_model_multi_ct_q_mpi.py,
    class: qDeepCT,
    checkpoint_resume: ,
    checkpoint_epoch: 0,
    checkpoint_chunk: 0,
    class_args: {
        sequence_length: 1000,
        n_cell_types: 181,
        sequence_embedding_length: 256,
        cell_type_embedding_length: 32,
        final_embedding_length: 256,
        n_genomic_features: 5,
    }
}
criterion: !obj:src.criterion.WeightedMSELossWithMPI {
  alpha: 0.0002
}
dataset: {
    debug: False,
    path: /home/msindeeva/DeepCT/src/dataset.py,
    class: EncodeDataset,
    ct_fold_ids: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/complete_clique1_with0/cell_types_random_ids_k10.npy,
    seq_fold_ids: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/complete_clique1_with0/split_intervals_no_overlap_k10.npy,
    train_sampler_class: LargeRandomSampler,
    train_sampler_args: {replacement: False},

    distinct_features_path: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/complete_clique1_with0/distinct_features_treatment.txt,
    target_features_path: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/complete_clique1_with0/target_features.txt,
    sampling_intervals_path: /mnt/datasets/DeepCT/dataset_data/Biox_et_al/complete_clique1_with0/target_intervals.bed,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],

    dataset_args: {
        reference_sequence_path: /mnt/datasets/DeepCT/male.hg19.fasta,
        target_path: /mnt/datasets/DeepCT/dataset_data/q_features_all/features2files_mapping.txt,
        cell_wise: True,
        multi_ct_target: True,
        sequence_length: 1000,
        center_bin_to_predict: 200,
        feature_thresholds: None,
        position_skip: 200,
        n_folds: 10,                    
        fold: 0,
        quantitative_features: True,
    },
    loader_args: {
        batch_size: 64,
        num_workers: 16,
        pin_memory: True,
    },
    train_transform: !obj:torchvision.transforms.Compose {
        transforms: [
            !obj:src.transforms.PermuteSequenceChannels {},
            !obj:src.transforms.RandomReverseStrand {
                p: 0.5,
            },
            !obj:src.transforms.LogTargets {
                pseudocount: 0.001
            },
            !obj:src.transforms.ClipTargets {
              amin: -1.0,
              amax: 4.0
            }
        ],
    },
    val_transform: !obj:torchvision.transforms.Compose {
        transforms: [
            !obj:src.transforms.PermuteSequenceChannels {},
            !obj:src.transforms.LogTargets {
                pseudocount: 0.001
            },
            !obj:src.transforms.ClipTargets {
              amin: -1.0,
              amax: 4.0
            }
        ]
    }
}
train_model: !obj:src.train.ct_masked_train.TrainEncodeDatasetModel {
    n_epochs: 30,
    report_stats_every_n_steps: 2000,
    save_track_metrics_during_training: True,
    save_checkpoint_every_n_steps: 2000,
    report_gt_feature_n_positives: 2,
    device: 'cuda:0',
    data_parallel: False,
    logging_verbosity: 2,
    metrics: {
        average_precision: !import sklearn.metrics.average_precision_score,
        r2: !import sklearn.metrics.r2_score,
    },
    metrics_transforms: {
        average_precision: !import src.transforms.meandev2prob,
        r2: !import src.transforms.meandev2val,
    },
    log_confusion_matrix: False,
}
output_dir: DeepCT_outputs/boix/qDeepCT_mpi/complete_clique1_with0/kfold_10folds_LR0001/no_overlap

random_seed: 1447
create_subdirectory: True
...
