---
ops: [evaluate]
model: {
    path: /home/arlapin/selene/manuscript/case2/deeper_deepsea_arch.py,
    class: DeeperDeepSEA,
    class_args: {
        sequence_length: 1000,
        n_targets: 919,
    },
    non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.IntervalsSampler {
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path: /mnt/datasets/DeepCT/male.hg19.fasta,
        blacklist_regions: hg19
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: /mnt/datasets/DeepCT/all_features/distinct_features.txt
    },
    target_path: /mnt/datasets/DeepCT/all_features/sorted_deepsea_data.bed.gz,
    intervals_path: /mnt/datasets/DeepCT/all_features/TF_intervals.txt,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],
    seed: 127,
    sequence_length: 1000,
    center_bin_to_predict: 200,
    feature_thresholds: 0.5,
}
evaluate_model: !obj:selene_sdk.EvaluateModel {
    features:  !obj:selene_sdk.utils.load_features_list {
        input_path: /mnt/datasets/DeepCT/all_features/distinct_features.txt,
    },
    n_test_samples: 640000,
    trained_model_path: /mnt/datasets/DeeperDeepSEA/example_deeperdeepsea.pth.tar,
    batch_size: 1024,
    report_gt_feature_n_positives: 0,
    use_cuda: True,
    data_parallel: True,
    output_dir: DeeperDeepSEA_output/,
    metrics: {
        accuracy: !import src.metrics.accuracy_score,
        precision: !import src.metrics.precision_score,
        recall: !import src.metrics.recall_score,
        roc_auc: !import sklearn.metrics.roc_auc_score,
        average_precision: !import sklearn.metrics.average_precision_score,
    },
    use_features_ord: [
        8988T|DNase|None,
        A549|DNase|None,
        Adult_CD4_Th0|DNase|None,
        AG04449|DNase|None,
        AG04450|DNase|None,
        AG09309|DNase|None,
        AG09319|DNase|None,
        AG10803|DNase|None,
        AoAF|DNase|None,
        AoSMC|DNase|None,
        BE2_C|DNase|None,
        BJ|DNase|None,
        Caco-2|DNase|None,
        CD20+|DNase|None,
        CD34+_Mobilized|DNase|None,
        Chorion|DNase|None,
        CLL|DNase|None,
        CMK|DNase|None,
        Fibrobl|DNase|None,
        FibroP|DNase|None,
        Gliobla|DNase|None,
        GM06990|DNase|None,
        GM12864|DNase|None,
        GM12865|DNase|None,
        GM12878|DNase|None,
        GM12891|DNase|None,
        GM12892|DNase|None,
        GM18507|DNase|None,
        GM19238|DNase|None,
        GM19239|DNase|None,
        GM19240|DNase|None,
        H1-hESC|DNase|None,
        H7-hESC|DNase|None,
        H9ES|DNase|None,
        HAc|DNase|None,
        HAEpiC|DNase|None,
        HA-h|DNase|None,
        HA-sp|DNase|None,
        HBMEC|DNase|None,
        HCFaa|DNase|None,
        HCF|DNase|None,
        HCM|DNase|None,
        HConF|DNase|None,
        HCPEpiC|DNase|None,
        HCT-116|DNase|None,
        HEEpiC|DNase|None,
        HeLa-S3|DNase|IFNa4h,
        HeLa-S3|DNase|None,
        Hepatocytes|DNase|None,
        HepG2|DNase|None,
        HFF|DNase|None,
        HFF-Myc|DNase|None,
        HGF|DNase|None,
        HIPEpiC|DNase|None,
        HL-60|DNase|None,
        HMEC|DNase|None,
        HMF|DNase|None,
        HMVEC-dAd|DNase|None,
        HMVEC-dBl-Ad|DNase|None,
        HMVEC-dBl-Neo|DNase|None,
        HMVEC-dLy-Ad|DNase|None,
        HMVEC-dLy-Neo|DNase|None,
        HMVEC-dNeo|DNase|None,
        HMVEC-LBl|DNase|None,
        HMVEC-LLy|DNase|None,
        HNPCEpiC|DNase|None,
        HPAEC|DNase|None,
        HPAF|DNase|None,
        HPDE6-E6E7|DNase|None,
        HPdLF|DNase|None,
        HPF|DNase|None,
        HRCEpiC|DNase|None,
        HRE|DNase|None,
        HRGEC|DNase|None,
        HRPEpiC|DNase|None,
        HSMM|DNase|None,
        HSMM_emb|DNase|None,
        HSMMtube|DNase|None,
        HTR8svn|DNase|None,
        Huh-7.5|DNase|None,
        Huh-7|DNase|None,
        HUVEC|DNase|None,
        HVMF|DNase|None,
        iPS|DNase|None,
        Ishikawa|DNase|4OHTAM_20nM_72hr,
        Ishikawa|DNase|Estradiol_100nM_1hr,
        Jurkat|DNase|None,
        K562|DNase|None,
        LNCaP|DNase|androgen,
        LNCaP|DNase|None,
        MCF-7|DNase|Hypoxia_LacAcid,
        MCF-7|DNase|None,
        Medullo|DNase|None,
        Melano|DNase|None,
        Monocytes-CD14+_RO01746|DNase|None,
        Myometr|DNase|None,
        NB4|DNase|None,
        NH-A|DNase|None,
        NHDF-Ad|DNase|None,
        NHDF-neo|DNase|None,
        NHEK|DNase|None,
        NHLF|DNase|None,
        NT2-D1|DNase|None,
        Osteobl|DNase|None,
        PANC-1|DNase|None,
        PanIsletD|DNase|None,
        PanIslets|DNase|None,
        pHTE|DNase|None,
        PrEC|DNase|None,
        ProgFib|DNase|None,
        RPTEC|DNase|None,
        RWPE1|DNase|None,
        SAEC|DNase|None,
        SKMC|DNase|None,
        SK-N-MC|DNase|None,
        SK-N-SH_RA|DNase|None,
        Stellate|DNase|None,
        T-47D|DNase|None,
        Th1|DNase|None,
        Th2|DNase|None,
        Urothelia|DNase|None,
        Urothelia|DNase|UT189,
        WERI-Rb-1|DNase|None,
        WI-38|DNase|4OHTAM_20nM_72hr,
        WI-38|DNase|None,
    ],
}
random_seed: 1447
...
