---
ops: [evaluate]
model: {
    path: /home/arlapin/selene/manuscript/case2/deeper_deepsea_arch.py,
    class: DeeperDeepSEA,
    class_args: {
        sequence_length: 1000,
        n_targets: 125,
    },
    non_strand_specific: mean
}
sampler: !obj:src.samplers.dnase_file_sampler.DNaseFileSampler {
    filepath: /mnt/datasets/DeepCT/dnase_features/test_data.bed,
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path: /mnt/datasets/DeepCT/male.hg19.fasta,
        blacklist_regions: hg19
    },
    n_cell_types: 125,
}
evaluate_model: !obj:src.evaluation.evaluate_model.EvaluateModel {
    features:  !obj:selene_sdk.utils.load_features_list {
        input_path: /mnt/datasets/DeepCT/dnase_features/distinct_features.txt,
    },
    n_test_samples: 64000,
    trained_model_path: /home/arlapin/DeepCT/DeepCT_outputs/DDS_trained_on_DNase/best_model.pth.tar,
    batch_size: 1000,
    report_gt_feature_n_positives: 0,
    use_cuda: True,
    data_parallel: True,
    log_cell_type_embeddings_to_tensorboard: False,
    metrics: {
        accuracy: !import src.metrics.accuracy_score,
        average_precision: !import sklearn.metrics.average_precision_score,
        f1: !import src.metrics.f1_score,
        precision: !import src.metrics.precision_score,
        recall: !import src.metrics.recall_score,
        roc_auc: !import sklearn.metrics.roc_auc_score,
    },
}
random_seed: 1447
...
