---
ops: [train, evaluate]
model: {
    path: /home/arlapin/selene/manuscript/case2/deeper_deepsea_arch.py,
    class: DeeperDeepSEA,
    class_args: {
        sequence_length: 1000,
        n_targets: 125,
    },
    non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.IntervalsSampler {
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path: /mnt/datasets/DeepCT/male.hg19.fasta,
        blacklist_regions: hg19
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: /mnt/datasets/DeepCT/dnase_features/distinct_features.txt
    },
    target_path: /mnt/datasets/DeepCT/dnase_features/sorted_deepsea_data.bed.gz,
    intervals_path: /mnt/datasets/DeepCT/dnase_features/TF_intervals.txt,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],
    seed: 127,
    sequence_length: 1000,
    center_bin_to_predict: 200,
    feature_thresholds: 0.5,
    mode: train,
}
train_model: !obj:selene_sdk.TrainModel {
    batch_size: 64,
    max_steps: 960000,
    report_stats_every_n_steps: 5000,
    report_gt_feature_n_positives: 0,
    n_validation_samples: 16000,
    n_test_samples: 640000,
    use_cuda: True,
    data_parallel: True,
    logging_verbosity: 2,
    metrics: {
        accuracy: !import src.metrics.accuracy_score,
        f1: !import src.metrics.f1_score,
        precision: !import src.metrics.precision_score,
        recall: !import src.metrics.recall_score,
        roc_auc: !import sklearn.metrics.roc_auc_score,
    },
}
output_dir: DeepCT_outputs/DDS_trained_on_DNase
random_seed: 1447
create_subdirectory: False
...
