---
ops: [train, evaluate]
lr: 0.00001
model: {
    path: src/dnase_only_model.py,
    class: DeepCT,
    class_args: {
        sequence_length: 1000,
        n_cell_types: 125,
        sequence_embedding_length: 128,
        cell_type_embedding_length: 32,
        final_embedding_length: 512,
        n_genomic_features: 1,
    },
    non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.MultiFileSampler {
    train_sampler: !obj:src.samplers.dnase_file_sampler.DNaseFileSampler {
        filepath: /mnt/datasets/DeepCT/dnase_features/train_data.bed,
        reference_sequence: !obj:selene_sdk.sequences.Genome {
            input_path: /mnt/datasets/DeepCT/male.hg19.fasta,
            blacklist_regions: hg19
        },
        n_cell_types: 125,
    },
    validate_sampler: !obj:src.samplers.dnase_file_sampler.DNaseFileSampler {
        filepath: /mnt/datasets/DeepCT/dnase_features/validate_data.bed,
        reference_sequence: !obj:selene_sdk.sequences.Genome {
            input_path: /mnt/datasets/DeepCT/male.hg19.fasta,
            blacklist_regions: hg19
        },
        n_cell_types: 125,
    },
    test_sampler: !obj:src.samplers.dnase_file_sampler.DNaseFileSampler {
        filepath: /mnt/datasets/DeepCT/dnase_features/test_data.bed,
        reference_sequence: !obj:selene_sdk.sequences.Genome {
            input_path: /mnt/datasets/DeepCT/male.hg19.fasta,
            blacklist_regions: hg19
        },
        n_cell_types: 125,
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: /mnt/datasets/DeepCT/dnase_features/distinct_features.txt
    },
}
train_model: !obj:src.train.train_dnase_only.TrainModel {
    batch_size: 2,
    max_steps: 50,
    report_stats_every_n_steps: 10,
    report_gt_feature_n_positives: 0,
    n_validation_samples: 100,
    n_test_samples: 100,
    use_cuda: True,
    data_parallel: True,
    logging_verbosity: 2,
    metrics: {
        accuracy: !import src.metrics.accuracy_score,
        average_precision: !import sklearn.metrics.average_precision_score,
        f1: !import src.metrics.f1_score,
        precision: !import src.metrics.precision_score,
        recall: !import src.metrics.recall_score,
        roc_auc: !import sklearn.metrics.roc_auc_score,
    },
}
output_dir: DeepCT_outputs/debug_v2
random_seed: 1447
create_subdirectory: True
...
