---
ops: [evaluate]

# !!!: You should copy model's source and its config from tensorboard "TEXT" section.
# If you don't do that, model can be loaded incorrectly without thrown exception.
model: {
    path: src/dnase_only_model.py,
    class: DeepCT,
    class_args: {
        sequence_length: 1000,
        n_cell_types: 125,
        sequence_embedding_length: 256,
        cell_type_embedding_length: 32,
        final_embedding_length: 256,
        n_genomic_features: 1,
    },
    non_strand_specific: mean
}

sampler: !obj:src.samplers.dnase_file_sampler.DNaseFileSampler {
    filepath: /mnt/datasets/DeepCT/dnase_features/test_data.bed,
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path: /mnt/datasets/DeepCT/male.hg19.fasta,
        blacklist_regions: hg19
    },
    n_cell_types: 125,
}

evaluate_model: !obj:src.evaluation.evaluate_model.EvaluateModel {
    features:  !obj:selene_sdk.utils.load_features_list {
        # NOTE: This file contains classes for the cell type labels.
        input_path: /home/vsfishman/DeepCT/distinct_features.classified_ct.txt,
    },
    n_test_samples: 64000,
    trained_model_path: /home/arlapin/DeepCT/DeepCT_outputs/deep_ct_v2/CosineAnnealingLR__quatro_head__0_04/checkpoint.pth.tar,
    batch_size: 100,
    report_gt_feature_n_positives: 0,
    use_cuda: True,
    data_parallel: True,
    metrics: {
        accuracy: !import src.metrics.accuracy_score,
        average_precision: !import sklearn.metrics.average_precision_score,
        f1: !import src.metrics.f1_score,
        precision: !import src.metrics.precision_score,
        recall: !import src.metrics.recall_score,
        roc_auc: !import sklearn.metrics.roc_auc_score,
    },
}
random_seed: 1447
...
