---
# based on encode_dnase_multi_ct_eval.yml from /home/msindeeva/DeepCT/model_configs, modified on Jun 23
# and get_predictions.yml from selene examples
ops: [analyze]

model: {
    path: src/deepct_model_multi_ct.py,
    class: DeepCT,
    class_args: { #TODO - do we need to provide this info to instantianse trained model?
        sequence_length: 1000,
        n_cell_types: 125,
        sequence_embedding_length: 256,
        cell_type_embedding_length: 32,
        final_embedding_length: 256,
        n_genomic_features: 1,
    }
}

# TODO: some values could be copied automatically from the model class
analyze_sequences: !obj:src.prediction.predict.AnalyzeSequences {
    trained_model_path: /home/msindeeva/DeepCT/DeepCT_outputs/encode/ct_v2/dnase/multi_ct/AdamW_COS_LR0001/2021-04-27-13-37-01/best_model.pth.tar,
    sequence_length: 1000,
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: /mnt/datasets/DeepCT/dataset_data/dnase/target_features.txt
    },
    distinct_features: !obj:selene_sdk.utils.load_features_list {
        input_path: /mnt/datasets/DeepCT/dataset_data/dnase/distinct_features.txt
    },
    batch_size: 128,
    device: 'cuda:2',
    data_parallel: False,
    n_cell_types: 125,
    reference_sequence: !obj:selene_sdk.sequences.Genome {
            input_path: /mnt/datasets/DeepCT/male.hg19.fasta
    },
    write_mem_limit: 75000
}

prediction: {
    input_path: /mnt/home/vsfishman/TheCellState/DeepCT/data/test_data/example_genomic_intervals.bed,
    sample_continuous: True,
    output_dir: /mnt/home/vsfishman/TheCellState/DeepCT/DeepCT_outputs/encode/ct_v2/dnase/multi_ct/AdamW_COS_LR0001/2021-04-27-13-37-01/prediction/,
    output_format: bigWig
}


random_seed: 1447
...
