---
ops: [train, evaluate]
lr: 0.00000001
model: {
    path: src/models/rpkm/rpkm_long_seq_balanced.py,
    class: DeepCT,
    class_args: {
        sequence_length: 100000,
        n_cell_types: 49,
        sequence_embedding_length: 256,
        cell_type_embedding_length: 32,
        final_embedding_length: 256,
        n_genomic_features: 1,
    },
    #non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.MultiFileSampler {
    train_sampler: !obj:src.samplers.rpkm_file_sampler_balanced.DNaseFileSampler {
        filepath: /home/evmalkin/DeepCT/src/data/train_data_rpkm_log.bed,
        reference_sequence: !obj:selene_sdk.sequences.Genome {
            input_path: /mnt/datasets/DeepCT/male.hg19.fasta,
            #blacklist_regions: hg19
        },
        n_cell_types: 49,
        sequence_length: 100000,
    },
    validate_sampler: !obj:src.samplers.rpkm_file_sampler_balanced.DNaseFileSampler {
        filepath: /home/evmalkin/DeepCT/src/data/validate_data_rpkm_log.bed,
        reference_sequence: !obj:selene_sdk.sequences.Genome {
            input_path: /mnt/datasets/DeepCT/male.hg19.fasta,
            #blacklist_regions: hg19
        },
        n_cell_types: 49,
        sequence_length: 100000,
    },
    test_sampler: !obj:src.samplers.rpkm_file_sampler_balanced.DNaseFileSampler {
        filepath: /home/evmalkin/DeepCT/src/data/test_data_rpkm_log.bed,
        reference_sequence: !obj:selene_sdk.sequences.Genome {
            input_path: /mnt/datasets/DeepCT/male.hg19.fasta,
            #blacklist_regions: hg19
        },
        n_cell_types: 49,
        sequence_length: 100000,
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: /home/evmalkin/DeepCT/src/data/rpkm_distinct_features.txt
    },
}
train_model: !obj:src.train.train_rpkm_balanced.TrainModel {
    batch_size: 8,
    validate_batch_size: 8,
    n_validation_samples: 5781,
    n_test_samples: 4709,
    max_steps: 150000,
    report_stats_every_n_steps: 2000,
    report_gt_feature_n_positives: 0,
    use_cuda: True,
    data_parallel: True,
    logging_verbosity: 2,
    embeddings_path: src/data/rpkm_feature_embeddings.csv,
    metrics: {        
        r2: !import sklearn.metrics.r2_score
    },
}
output_dir: DeepCT_outputs/expression_long_seq/rpkm_results_debug
random_seed: 1447
create_subdirectory: False
...
