---
ops: [train, evaluate]
model: {
    path: src/deep_ct_model.py,
    class: DeepCT,
    class_args: {
        sequence_length: 1000,
        n_cell_types: 125,
        cell_type_embedding_length: 10,
        n_genomic_features: 1,
    },
    non_strand_specific: mean
}
sampler: !obj:src.deep_ct_sampler.IntervalsSampler {
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        input_path: /mnt/datasets/DeepCT/male.hg19.fasta,
        blacklist_regions: hg19
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: model_configs/dnase_features.txt
    },
    target_path: /mnt/datasets/DeepCT/dnase_features/sorted_deepsea_data.bed.gz,
    intervals_path: /mnt/datasets/DeepCT/dnase_features/TF_intervals.txt,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],
    seed: 127,
    sequence_length: 1000,
    center_bin_to_predict: 200,
    feature_thresholds: 0.5,
    mode: train,
    save_datasets: [train, test, validate]
}
train_model: !obj:selene_sdk.TrainModel {
    batch_size: 64,
    max_steps: 960000,
    report_stats_every_n_steps: 5000,
    n_validation_samples: 16000,
    n_test_samples: 640000,
    use_cuda: True,
    data_parallel: True,
    logging_verbosity: 2
}
output_dir: DeepCT_outputs/
random_seed: 1447
create_subdirectory: False
...
